GLOBAL_LIST_EMPTY(all_observable_events)
GLOBAL_VAR_INIT(shit_left, 0)
GLOBAL_VAR_INIT(piss_left, 0)
GLOBAL_VAR_INIT(deaths_in_space,0)
GLOBAL_VAR_INIT(total_deaths,0)
GLOBAL_VAR_INIT(teeth_lost,0)
GLOBAL_LIST_EMPTY(initialTypeIcon)